### **Module 2: Python for Data Analysis**

#### **NumPy**

**Array**

- Tipe data terstruktur yang menyimpan data dengan tipe data yang seragam.
- Array bersifat mutable.
- Index dimulai dari 0.
- Bisa berbentuk 1D, 2D, 3D, .... nD
- Perbedaan array dengan matrix pada NumPy adalah kalau matrix hanya terbatas maksimal 2D saja, dan semua operasi yang bisa dilakukan
    matrix, bisa juga dilakukan oleh array. Jadi, lebih baik gunakan array saja.

**Dimensi pada array**

- Jumlah index yang dibutuhkan untuk memanggil suatu elemen.
- Array 1D punya 1 inderx --> vector.
- Array 2D punya 2 index --> matrix.
- Array 3D punya 3 index --> 3D array.
- Array nD punya nD index --> nD array.

**NumPy**

- NumPy --> Numerical Python.
- Library Python untuk mengelola data array.
- Bisa digunakan untuk operasi matrix, aljabar linear, dan matematika tingkat lanjut.
- Kecepatan operasi dengan array bisa 50x lebih cepat daripada list.
- Function untuk NumPy Array banyak digunakan untuk pekerjaan data science.

In [1]:
# Import library
import numpy as np

#### **Create Array**

In [2]:
# Membuat array dari sebuah list
list_angka = [[1, 2, 3], [4, 5, 6], [7, 8, 9]] # nested list (2D)

np.array(list_angka)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
# Array berisi angka berurut
np.arange(start=0, stop= 12, step=2)

array([ 0,  2,  4,  6,  8, 10])

In [4]:
# Array berisi angka 0
# Biasanya digunakan untuk membuat contoh dataset yang berisi hanya angka 0 saja

a = np.zeros(3)
print(a)
print(type(a))

[0. 0. 0.]
<class 'numpy.ndarray'>


In [5]:
# Array berisi angka 0
np.zeros((2, 3)) # (baris, kolom)

array([[0., 0., 0.],
       [0., 0., 0.]])

In [6]:
# Array berisi angka 1
# Biasanya digunakan untuk membuat contoh dataset berisi angka 1 saja
np.ones((5, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [7]:
# Array yang membagi sekian elemen dengan interval yang sama
np.linspace(start=0, stop=100, num=5)

array([  0.,  25.,  50.,  75., 100.])

In [8]:
np.linspace(0, 10, 2)

array([ 0., 10.])

**Membuat array berisi angka random**

- rand()
- randn()
- randint()

In [9]:
# rand()
# Array berisi angka random 0-1
np.random.rand(3)

array([0.79541522, 0.78659723, 0.07843689])

In [10]:
# 2D array
np.random.rand(3, 3)

array([[0.46935493, 0.69701651, 0.19385908],
       [0.03977089, 0.99076081, 0.50789437],
       [0.02273692, 0.11792569, 0.62760407]])

In [11]:
# randn()
# Array berisi angka random terdistribusi normal dengan rata-rata = 0 dan variance = 1 (atau standar deviasi mendekati 1 --> +- 1).
np.random.randn(3, 2)

array([[ 0.818296  , -0.84392155],
       [-1.46792431, -0.77684032],
       [-0.05355061,  0.75155457]])

In [12]:
np.random.randn(2)

array([0.26632247, 0.26537467])

In [13]:
# randint()
# Array yang berisi angka random integer
np.random.randint(1, 100)

67

In [14]:
np.random.randint(low=1, high=100, size=10)

array([57, 67, 73, 92,  3, 15, 60, 22, 95, 52])

In [15]:
np.random.randint(1, 100, 10)

array([11, 99, 76,  7, 98, 68, 68, 29, 88, 74])

**Attributes and Methods**

In [16]:
# Mengubah list jadi array
list1 = [85, 72, 42, 33, 69,  5, 66, 75, 92, 15]
arr1 = np.array(list1)
print(arr1)
print(type(arr1))

[85 72 42 33 69  5 66 75 92 15]
<class 'numpy.ndarray'>


In [17]:
print(list1)
print(type(list1))

[85, 72, 42, 33, 69, 5, 66, 75, 92, 15]
<class 'list'>


In [18]:
# Mengubah list 2D jadi array 2D
list2 = [[98, 69, 1], [22, 34, 23], [10, 92, 35]]
arr2 = np.array(list2)
arr2

array([[98, 69,  1],
       [22, 34, 23],
       [10, 92, 35]])

In [19]:
# Melihat bentuk dari array
arr1.shape

(10,)

In [20]:
# Mengubah bentuk/dimensi array jadi 2D
# Jumlah item sebelum dan sesudah reshape harus sesuai
arr1.reshape(1, 10)

array([[85, 72, 42, 33, 69,  5, 66, 75, 92, 15]])

In [21]:
arr1.reshape(2, 5)

array([[85, 72, 42, 33, 69],
       [ 5, 66, 75, 92, 15]])

In [22]:
arr1.reshape(5, 2)

array([[85, 72],
       [42, 33],
       [69,  5],
       [66, 75],
       [92, 15]])

In [23]:
arr2 = arr1.copy()
arr2

array([85, 72, 42, 33, 69,  5, 66, 75, 92, 15])

In [24]:
arr2.reshape(2, 5)

array([[85, 72, 42, 33, 69],
       [ 5, 66, 75, 92, 15]])

In [25]:
# Mengubah array 2D menjadi 1D
arr2.reshape(-1)

array([85, 72, 42, 33, 69,  5, 66, 75, 92, 15])

In [26]:
arr1

array([85, 72, 42, 33, 69,  5, 66, 75, 92, 15])

In [27]:
# Nilai maksimum pada suatu array
arr1.max()

92

In [28]:
# Mencari index dari nilai maksimum pada suatu array
arr1.argmax()

8

In [29]:
# Nilai minimum pada suatu array
arr1.min()

5

In [30]:
# Mencari index dari nilai minimum pada suatu array
arr1.argmin()

5

In [31]:
# Cek tipe data dari isi suatu array
arr1.dtype # Array hanya menampung 1 tipe data yang sama.

dtype('int32')

In [32]:
# Cek tipe data dari suatu variabel
type(arr1)

numpy.ndarray

**Indexing**

In [33]:
arr = np.arange(0, 100, 2)
arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [34]:
# Indexing 1 elemen
arr[7]

14

In [35]:
# Indexing [start:stop:step] urutan maju
arr[0:7:2] # start di index 0, stop di index 7, stepnya loncat 2 index

array([ 0,  4,  8, 12])

In [36]:
# Indexing urutan muntur
arr[8:0:-2]

array([16, 12,  8,  4])

In [37]:
# Mengganti nilai dari index tertentu
arr[0:5] = 100
arr

array([100, 100, 100, 100, 100,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98])

**Slicing**

Hati-hati dengan slicing array. Jika yang di-slice berubah, array di variabel awal akan ikut berubah.

In [38]:
arr2 = np.arange(0, 11, 1)
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [39]:
slicing = arr2[0:5]
slicing

array([0, 1, 2, 3, 4])

In [40]:
# Mengganti nilai pada seluruh elemen
slicing[:] = 100
slicing

array([100, 100, 100, 100, 100])

In [41]:
arr2

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

**Untuk mengatasinya, kita harus gunakan np.copy() terlebih dahulu untuk membuat duplikat pada variabel yang ingin kita ubah nilainya.**

In [42]:
arr3 = arr2.copy()
arr3 # Variabel yang nilainya berisi sama dengan arr2, tapi kita bisa mengubah-ubah nilainya tanpa mengganggu arr2

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [43]:
arr3[:] = 10
arr3

array([10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10])

In [44]:
arr2

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

**Indexing & slicing array 2D**

In [45]:
# Membuat array 2D
arr_2d = np.array([[10, 15, 20], [25, 30, 35], [40, 45, 50]])
arr_2d

array([[10, 15, 20],
       [25, 30, 35],
       [40, 45, 50]])

In [46]:
arr_2d.shape

(3, 3)

In [47]:
# Slicing baris index 0
arr_2d[0]

array([10, 15, 20])

In [48]:
# Slicing baris index 0, lalu slicing kolom index 1
arr_2d[0][1] # --> [0] adalah index baris, [1] adalah index kolom

15

In [49]:
arr_2d[1][2]

35

In [50]:
arr_2d

array([[10, 15, 20],
       [25, 30, 35],
       [40, 45, 50]])

In [51]:
# Slicing baris index 0, 1 dan kolom 1, 2
arr_2d[:2, 1:]

array([[15, 20],
       [30, 35]])

In [52]:
# Slicing baris index [0:2], lalu slicing lari baris index [1:akhir]
# Jangan slicing seperti cara ini.
arr_2d[:2][1:]

array([[25, 30, 35]])

**Fancy indexing**

In [53]:
arr = np.arange(0, 1100, 100)
arr

array([   0,  100,  200,  300,  400,  500,  600,  700,  800,  900, 1000])

In [54]:
# Indexing untuk index yang tidak berurutan. Caranya adalah dengan menggunakan double kurung siku.
arr[[3, 9, 2]]

array([300, 900, 200])

In [55]:
arr_2d

array([[10, 15, 20],
       [25, 30, 35],
       [40, 45, 50]])

In [56]:
# Double bracket untuk indexing menandai fancy indexing.
# Output yang dihasilkan adalah angka index yang sesuai dengan yang kita definisikan
arr_2d[[0, 2]] # Kita mengambil semua data dari index baris 0 dan 2

array([[10, 15, 20],
       [40, 45, 50]])

In [57]:
# Hanya 1 bracket. Berarti kita mengambil data baris index ke-0 pada kolom ke-2.
arr_2d[0, 2]

20

In [58]:
# Contoh 3D array
a = np.random.rand(3, 3, 3)
a

array([[[0.24531695, 0.38176318, 0.4348898 ],
        [0.15695959, 0.60783771, 0.18963496],
        [0.02656342, 0.61788907, 0.54047761]],

       [[0.16636947, 0.63634653, 0.20139529],
        [0.08964094, 0.30217849, 0.79213888],
        [0.42840254, 0.25070825, 0.99782524]],

       [[0.82499058, 0.10415713, 0.14914331],
        [0.8924403 , 0.1606631 , 0.74606489],
        [0.48160509, 0.01309772, 0.86358871]]])

In [59]:
# Fancy indexing 3D array sama saja dengan 2D
a[[0, 2]]

array([[[0.24531695, 0.38176318, 0.4348898 ],
        [0.15695959, 0.60783771, 0.18963496],
        [0.02656342, 0.61788907, 0.54047761]],

       [[0.82499058, 0.10415713, 0.14914331],
        [0.8924403 , 0.1606631 , 0.74606489],
        [0.48160509, 0.01309772, 0.86358871]]])

**Conditional Selection**

In [60]:
arr = np.arange(0, 11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [61]:
# Condition
# Mengembalikan boolean
arr > 4

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True])

In [62]:
# Condition disimpan dalam variabel
bool_arr = arr > 4
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True])

In [63]:
# Mengembalikan nilai yang kondisinya True
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [64]:
# Tanpa disimpan ke variabel
arr[arr > 4]

array([ 5,  6,  7,  8,  9, 10])

**Arithmetic 1D**

In [65]:
arr = np.arange(0, 11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [66]:
# Menambahkan angka 3 pada setiap elemen di array
arr + 3

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [67]:
# Pembagian
1/arr

C:\Users\maulialwan\AppData\Local\Temp/ipykernel_10416/3398525889.py:2: RuntimeWarning: divide by zero encountered in true_divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [68]:
# Perkalian
arr*arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

**Arithmetic 2D**

In [69]:
# Array 1D
arr_1d = np.array([1, 2, 3])
arr_1d

array([1, 2, 3])

In [70]:
arr_1d.shape 

(3,)

In [71]:
arr_2d

array([[10, 15, 20],
       [25, 30, 35],
       [40, 45, 50]])

In [72]:
# Operasi matematika untuk array 2D
arr_2d * 2

array([[ 20,  30,  40],
       [ 50,  60,  70],
       [ 80,  90, 100]])

In [73]:
arr_1d

array([1, 2, 3])

In [74]:
arr_2d

array([[10, 15, 20],
       [25, 30, 35],
       [40, 45, 50]])

In [75]:
# Mengalikan array 2D dengan array 1D
# Bisa dilakukan asalkan jumlah kolomnya sama
arr_2d * arr_1d

array([[ 10,  30,  60],
       [ 25,  60, 105],
       [ 40,  90, 150]])

In [76]:
# Pembagian pada array 2D
arr_2d / arr_2d

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

**Function**

In [77]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [78]:
# Akar kuadrat
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [79]:
# Sin
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [80]:
# Logarithmic
np.log(arr)

C:\Users\maulialwan\AppData\Local\Temp/ipykernel_10416/1965383145.py:2: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

In [81]:
# Exponential
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

**Function lain**

In [82]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [83]:
# Menyelipkan sebuah elemen pada index tertentu
np.insert(arr, 5, 100) # (nama_variabel, angka_index, nilai yang mau diselipkan)

array([  0,   1,   2,   3,   4, 100,   5,   6,   7,   8,   9,  10])

In [84]:
# Menghapus element pada index tertentu
np.delete(arr, 2)

array([ 0,  1,  3,  4,  5,  6,  7,  8,  9, 10])

In [85]:
# Menambahkan elemen di index terakhir
np.append(arr, 100)

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10, 100])

In [86]:
# Mengghabungkan 2 array terpisah menjadi 1 array
# Jika menambahkan di baris, maka jumlah kolom harus sama.
# Jika menambhakan di kolom, maka jumlah baris harus sama.

a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[19, 20, 30]])

np.concatenate((a, b))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [19, 20, 30]])

In [87]:
np.concatenate((a, b)).T # Transpose

array([[ 1,  4, 19],
       [ 2,  5, 20],
       [ 3,  6, 30]])

In [88]:
# Menggabungkan pada baris, jumlah kolom harus sama
np.concatenate((b, a), axis=0)

array([[19, 20, 30],
       [ 1,  2,  3],
       [ 4,  5,  6]])

In [89]:
# Menggabungkan pada kolom, jumlah baris harus sama
np.concatenate((a.T, b.T), axis=1)

array([[ 1,  4, 19],
       [ 2,  5, 20],
       [ 3,  6, 30]])

In [90]:
# Mengubah array menjadi 1D dengan menggunakan axis=None
np.concatenate((a, b), axis=None)

array([ 1,  2,  3,  4,  5,  6, 19, 20, 30])

**np.where()**

In [91]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [92]:
# Mengubah elemen pada index yang kondisinya True dengan method where()
np.where(arr > 5, 1, arr)

array([0, 1, 2, 3, 4, 5, 1, 1, 1, 1, 1])

In [93]:
np.where(arr > 5, 1, 0) # Seperti if else condition

array([0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1])

In [94]:
arr_2d

array([[10, 15, 20],
       [25, 30, 35],
       [40, 45, 50]])

In [95]:
np.where(arr_2d <= 30, 0, arr_2d+10)

array([[ 0,  0,  0],
       [ 0,  0, 45],
       [50, 55, 60]])

**Latihan**

1. Buatlah operasi penjumlahan pada array (3, 3) dan (1, )

In [96]:
a = np.array(
    [[1, 2, 3],
     [10, 20, 30],
     [100, 200, 300]])

b = np.array([5])

a+b

array([[  6,   7,   8],
       [ 15,  25,  35],
       [105, 205, 305]])

2. Buatlah operasi penjumlahan pada array (3, 3) dan (3,)

In [97]:
a = np.array([[1, 2, 3], [10, 20, 30], [100, 200, 300]])
b = np.array([5, 6, 7])

a+b

array([[  6,   8,  10],
       [ 15,  26,  37],
       [105, 206, 307]])

3. Buatlah operasi penjumlahan pada array (3, 3) dan (3, 3)

In [98]:
# Operasi penjumlahan pada array (3, 3) dan (3, 3) 
a = np.array([[1, 2, 3], [10, 20, 30], [100, 200, 300]])
b = np.array([[5, 6, 7], [8, 9, 10], [11, 12, 13]])

a+b

array([[  6,   8,  10],
       [ 18,  29,  40],
       [111, 212, 313]])