### **Modul 2: Data Analysis**

<hr></hr>


**Latihan NumPy**

In [1]:
# Import library
import numpy as np

## **No.1**

In [2]:
# Agar saat generate bilangan random tidak berubah
np.random.seed(0)

# Buat array 1 dimensi ukuran 36 dengan data random Integer, simpan dalam variabel bernama myArray
myArray = np.random.randint(1, 100, 36)
myArray 

array([45, 48, 65, 68, 68, 10, 84, 22, 37, 88, 71, 89, 89, 13, 59, 66, 40,
       88, 47, 89, 82, 38, 26, 78, 73, 10, 21, 81, 70, 80, 48, 65, 83, 89,
       50, 30])

## **No.2**

In [3]:
# Buat 3 Matrix dengan dimensi berbeda
Soal2_1 = myArray.reshape(2, 18) 
Soal2_2 = myArray.reshape(9, 4)
Soal2_3 = myArray.reshape(2, 6, 3)

print ('\n Array 1:\n', Soal2_1)
print ('\n Array 2:\n', Soal2_2)
print ('\n Array 3D:\n', Soal2_3)


 Array 1:
 [[45 48 65 68 68 10 84 22 37 88 71 89 89 13 59 66 40 88]
 [47 89 82 38 26 78 73 10 21 81 70 80 48 65 83 89 50 30]]

 Array 2:
 [[45 48 65 68]
 [68 10 84 22]
 [37 88 71 89]
 [89 13 59 66]
 [40 88 47 89]
 [82 38 26 78]
 [73 10 21 81]
 [70 80 48 65]
 [83 89 50 30]]

 Array 3D:
 [[[45 48 65]
  [68 68 10]
  [84 22 37]
  [88 71 89]
  [89 13 59]
  [66 40 88]]

 [[47 89 82]
  [38 26 78]
  [73 10 21]
  [81 70 80]
  [48 65 83]
  [89 50 30]]]


## **No.3**

In [4]:
# Nilai Minimun dan Maksimum
Soal3_Min = myArray.min()
Soal3_Max = myArray.max()

# Index dari Nilai Minimun dan Maksimum
Soal3_ArgMin = myArray.argmin()
Soal3_ArgMax = myArray.argmax()

print (f'Nilai minimum: {Soal3_Min}')
print (f'Nilai maximum: {Soal3_Max}')
print (f'Nilai minimun ({Soal3_Min}) berada pada index: {Soal3_ArgMin}')
print (f'Nilai maximum ({Soal3_Max}) berada pada index: {Soal3_ArgMax}')

Nilai minimum: 10
Nilai maximum: 89
Nilai minimun (10) berada pada index: 5
Nilai maximum (89) berada pada index: 11


## **No.4**

In [5]:
myArray

array([45, 48, 65, 68, 68, 10, 84, 22, 37, 88, 71, 89, 89, 13, 59, 66, 40,
       88, 47, 89, 82, 38, 26, 78, 73, 10, 21, 81, 70, 80, 48, 65, 83, 89,
       50, 30])

In [6]:
# Fancy Indexing, dengan double bracket
Soal4 = myArray[[3, 5, 30, 12, 15, 8, 24, 14, 22]]
Soal4

array([68, 10, 48, 89, 66, 37, 73, 59, 26])

In [7]:
# reshape
Soal4.reshape(3,3)

array([[68, 10, 48],
       [89, 66, 37],
       [73, 59, 26]])

In [8]:
Soal4

array([68, 10, 48, 89, 66, 37, 73, 59, 26])

## **No.5**

In [9]:
# Conditional Statement
Soal5 = Soal4.reshape(3, 3)[Soal4.reshape(3, 3) > 50]
Soal5

array([68, 89, 66, 73, 59])

In [10]:
# Conditional Statement
Soal5 = Soal4[Soal4 > 50]
Soal5

array([68, 89, 66, 73, 59])

In [11]:
Soal4 > 50

array([ True, False, False,  True,  True, False,  True,  True, False])

In [12]:
Soal4[[ True, False, False, False, False, False, False,  True,  True]]

array([68, 59, 26])

## **No.6**

In [13]:
# Linspace
Soal6 = np.linspace(0, 100, num=5)
Soal6

array([  0.,  25.,  50.,  75., 100.])

In [14]:
# Kalau np.arange outputnya integer
np.arange(0, 101, 25)

array([  0,  25,  50,  75, 100])

## **No.7**

In [15]:
# Buat Array Isi 10
N = int(input('Masukkan nilai N: '))
print(f'N yang diinputkan adalah {N}')

Soal7 = np.ones((N, N))*8
Soal7

N yang diinputkan adalah 10


array([[8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])

In [16]:
np.full((3, 3), 8)

array([[8, 8, 8],
       [8, 8, 8],
       [8, 8, 8]])

In [17]:
np.ones((1,3))

array([[1., 1., 1.]])

In [18]:
np.array([['Andi', 3, 'Jakarta'], ['Budi', 7, 'Bandung']])

array([['Andi', '3', 'Jakarta'],
       ['Budi', '7', 'Bandung']], dtype='<U7')

## **No.8**

In [19]:
arrayA = np.arange(1, 13).reshape(3, 4)
arrayA

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [20]:
arrayB = np.arange(100, 401, 100).reshape(4, 1)
arrayB

array([[100],
       [200],
       [300],
       [400]])

In [21]:
arrayB.T

array([[100, 200, 300, 400]])

In [22]:
# Gabungkan arrayA dan arrayB
arrayC = np.concatenate((arrayA, arrayB.T), axis=0)
arrayC

array([[  1,   2,   3,   4],
       [  5,   6,   7,   8],
       [  9,  10,  11,  12],
       [100, 200, 300, 400]])

## **No.9**

In [23]:
# Slicing array --> array[row, column]
arrayC[1:3 , 2:]

array([[ 7,  8],
       [11, 12]])

## **No.10**

In [24]:
# Indexing array 
arrayC[3, 1]

200

In [25]:
arrayC[3][1]

200

In [26]:
np.where(arrayC==200)

(array([3], dtype=int64), array([1], dtype=int64))

## **No. 11**

In [27]:
# 11. Dari 2 array berikut, tampilkan index yang nilainya sama antara array a dan b.
# a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])
# b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])

# Output:
# array([1, 3, 5, 7])

In [2]:
# Solusi 11
a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])
b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])

np.where(a == b)

(array([1, 3, 5, 7], dtype=int64),)

## **No. 12**

In [29]:
# 12. Dari array berikut, tampilkan nilai yang range-nya antara 5 dan 10!
# x = np.array([2, 6, 1, 9, 10, 3, 27])

# Output:
# array([6, 9, 10])

In [30]:
# Solusi 12
a = np.array([2, 6, 1, 9, 10, 3, 27])

index = np.where((a >= 5) & (a <= 10))
a[index]

array([ 6,  9, 10])

In [31]:
# Cara lain
a[(a >= 5) & (a <= 10)]

# Jika ada lebih dari 1 kondisi:
# AND pada Numpy dan Pandas harus memakai tanda '&'
# OR pada Numpy dan Pandas harus memakai tanda '|'

array([ 6,  9, 10])

## **No. 13**

In [32]:
# 13. Jika kode berikut dijalankan --> arr = np.arange(9).reshape(3, 3)
# outputnya adalah:
# array([[0, 1, 2],
#        [3, 4, 5],
#        [6, 7, 8]])

# Bagaimana mengubah output di atas menjadi seperti berikut?

# Output: 
# array([[1, 0, 2],
#        [4, 3, 5],
#        [7, 6, 8]])

In [33]:
arr = np.arange(9).reshape(3, 3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [34]:
# Solusi 13
arr[:, [1, 0, 2]]

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

## **No. 14**

In [35]:
# 14. Jika kode berikut dijalankan --> arr = np.arange(9).reshape(3, 3)
# outputnya adalah:
# array([[0, 1, 2],
#        [3, 4, 5],
#        [6, 7, 8]])

# Bagaimana mengubah output di atas menjadi seperti berikut?

# Output: 
# array([[3, 4, 5],
#        [0, 1, 2],
#        [6, 7, 8]])

In [36]:
# Solusi 14
arr[[1, 0, 2], :]

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

## **No. 15**

In [37]:
# 15. Jika kode berikut dijalankan --> arr = np.arange(9).reshape(3, 3)
# outputnya adalah:
# array([[0, 1, 2],
#        [3, 4, 5],
#        [6, 7, 8]])

# Bagaimana mengubah output di atas menjadi seperti berikut?

# Output: 
# array([[2, 1, 0],
#        [5, 4, 3],
#        [8, 7, 6]])

In [38]:
arr[:, ::-1]

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

In [39]:
x = np.array([], dtype=np.float64)
x

array([], dtype=float64)